CREATE DATABASE reservationDB;

USE reservationDB;

CREATE TABLE RESERVATION (
    IDENTIFICATION varchar(15)NOT NULL PRIMARY KEY,
    NAME varchar(255) NOT NULL,
    ROOM_NUMBER INT NOT NULL,
	CHECKIN DATETIME2 NOT NULL,
	CHECKOUT DATETIME2 NOT NULL,
	DEPARTURE DATETIME2 NOT NULL,
	STATUS BIT ,
	FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM(ROOM_NUMBER)
);

CREATE TABLE ROOM (
    ROOM_NUMBER INT UNIQUE NOT NULL,
    STATUS BIT
	);


	INSERT INTO [dbo].[ROOM]([ROOM_NUMBER],[STATUS]) VALUES(333,1),(666666,1),(999999999,1)
	
