export  enum ActionTypes {
    GET_RESERVATIONS_REQUEST    = "GET_RESERVATIONS_REQUEST",
    GET_RESERVATIONS_SUCCESS    = "GET_RESERVATIONS_SUCCESS",
    GET_RESERVATIONS_FAIL       = "GET_RESERVATIONS_FAIL",

    GET_ROOMS_REQUEST    = "GET_ROOMS_REQUEST",
    GET_ROOMS_SUCCESS    = "GET_ROOMS_SUCCESS",
    GET_ROOMS_FAIL       = "GET_ROOMS_FAIL",
}